//
//  NumberPickerWheel.swift
//  PLog
//
//  A compact scrollable wheel picker for numeric values (weight, reps, sets, age, height, …)
//  — flick to the right number instead of tapping +/- repeatedly.
//

import SwiftUI

struct NumberPickerWheel: View {
    let title: String
    @Binding var value: Double
    var step: Double = 1
    var range: ClosedRange<Double> = 0...999
    var unit: String? = nil
    var width: CGFloat = 100
    var height: CGFloat = 120
    /// How to render each wheel row's number (e.g. drop trailing ".0").
    var format: (Double) -> String = { WeightFormatter.string($0) }

    /// Every selectable value, generated by index so floating-point steps (e.g. 2.5) never
    /// drift out of alignment with the bound `value` the way repeated addition would.
    private var values: [Double] {
        let count = Int(((range.upperBound - range.lowerBound) / step).rounded()) + 1
        return (0..<max(count, 1)).map { range.lowerBound + Double($0) * step }
    }

    var body: some View {
        VStack(spacing: 2) {
            Text(title)
                .font(.caption)
                .foregroundStyle(.secondary)

            Picker(title, selection: $value) {
                ForEach(values, id: \.self) { rowValue in
                    rowLabel(rowValue).tag(rowValue)
                }
            }
            .pickerStyle(.wheel)
            .frame(width: width, height: height)
            .clipped()
            // A light tick per row scrolled past, matching the feel of a physical dial.
            .sensoryFeedback(.selection, trigger: value)
        }
    }

    private func rowLabel(_ rowValue: Double) -> some View {
        HStack(spacing: 2) {
            Text(format(rowValue))
                .font(.body.monospacedDigit())
            if let unit {
                Text(unit)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
        }
    }
}

extension NumberPickerWheel {
    /// Convenience initializer for an integer value (e.g. reps, sets, age).
    init(
        title: String,
        intValue: Binding<Int>,
        step: Int = 1,
        range: ClosedRange<Int> = 0...999,
        unit: String? = nil,
        width: CGFloat = 90,
        height: CGFloat = 120
    ) {
        self.title = title
        self._value = Binding(
            get: { Double(intValue.wrappedValue) },
            set: { intValue.wrappedValue = Int($0.rounded()) }
        )
        self.step = Double(step)
        self.range = Double(range.lowerBound)...Double(range.upperBound)
        self.unit = unit
        self.width = width
        self.height = height
        self.format = { String(Int($0)) }
    }
}

#Preview {
    struct Demo: View {
        @State private var weight = 62.5
        @State private var reps = 8
        var body: some View {
            HStack(spacing: 20) {
                NumberPickerWheel(title: "Weight", value: $weight, step: 2.5, range: 0...500, unit: "kg", width: 120)
                NumberPickerWheel(title: "Reps", intValue: $reps, range: 0...100)
            }
            .padding()
        }
    }
    return Demo()
}
